In [1]:
# tutorial on eager exec tensorflow:
# https://www.tensorflow.org/guide/eager

In [2]:
import os
import tensorflow as tf
import cProfile

In [3]:
tf.__version__

'2.1.0'

In [4]:
tf.executing_eagerly()

True

In [5]:
x = [[2.]]
m = tf.matmul(x, x)
print('hello, {}'.format(m))

hello, [[4.]]


In [6]:
a = tf.constant([[1, 2], [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
# broadcasting
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [8]:
# operator overloading
print(a * b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [10]:
# use numpy
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [11]:
print(a.numpy())

[[1 2]
 [3 4]]


In [14]:
# computing gradients
w = tf.Variable([1.0])
with tf.GradientTape() as tape:
    loss = w * w

grad = tape.gradient(loss, w) # compute dloss/dw
print(grad) # 2 * w = 2 ?

tf.Tensor([2.], shape=(1,), dtype=float32)
